# Generated by Django 4.1.3 on 2022-11-30 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='competition',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_country', to='data.country'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_sport', to='data.sport'),
        ),
        migrations.AlterField(
            model_name='country',
            name='abbreviation',
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_city', to='data.state')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_country', to='data.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_state', to='data.state')),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_country', to='data.country'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=5)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_country', to='data.country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_state', to='data.state')),
            ],
        ),
    ]
