# Generated by Django 4.1.3 on 2022-12-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0002_city_date_modified_country_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='images/countries'),
        ),
    ]
