# Generated by Django 4.1.3 on 2022-12-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0005_continent_country_is_active_country_is_independent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='flag',
            field=models.ImageField(blank=True, null=True, upload_to='images/states'),
        ),
    ]
